### ISSUE TITLE
.NET version issue?

### ISSUE THREAD

**Issue by JohnGilbertson** [oocx/acme.net#2]
Trying to run the cleint and I get:

Unhandled Exception: System.MissingMethodException: Method not found: '!!0[] Sys
tem.Array.Empty()'.
   at Oocx.ACME.Console.ContainerConfiguration.Configure(Options options)
   at Oocx.ACME.Console.Program.Execute(Options options) in C:\projects\acme-net
\src\Oocx.ACME.Console\Program.cs:line 32
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Ac
tion`1 action)
   at Oocx.ACME.Console.Program.Main(String[] args) in C:\projects\acme-net\src\
Oocx.ACME.Console\Program.cs:line 20
   at Oocx.ACME.CLRConsole.Program.Main(String[] args)

From a quick search it's a .NET 4.6/4.5 issue

**Comment by oocx** [comment]
Thank you for reporting this issue. I will investigate if I can target .NET 4.5 instead of 4.6.

**Comment by oocx** [comment]
I tried to change the framework to 4.5.2. However, the code is already using .NET 4.6 features. Dependencies for 4.5.2 would also need to be specified different than for 4.6/dnx4.6 in project.json, and I don't want to invest too much time in figuring out how I would have to change those. I therefore decided not to add .net 4.5.2 support.

I would accept a pull request if you figure out the necessary changes :).
